version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/zalate1/al1/main/al1.sh

        

workflows:
    version: 2.1
    build:
        jobs:
            - Devop